[[plugins]]
repo = 'tpope/vim-commentary'
on_cmd = ['Commentary']
on_map = ['gcc', 'gc']

[[plugins]]
repo = 'AndrewRadev/splitjoin.vim'
on_cmd = ['SplitjoinJoin', 'SplitjoinSplit']
on_map = ['gS', 'gJ']

[[plugins]]
repo  = 'ekalinin/Dockerfile.vim'
on_ft = ['dockerfile']

[[plugins]]
repo  = 'uarun/vim-protobuf'
on_ft = 'protobuf'

[[plugins]]
repo  = 'stephpy/vim-yaml'
on_ft = ['yml', 'yaml']

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd', 'md']

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
let g:go_def_mode='gopls'
let g:go_info_mode='gopls'
let g:go_def_mapping_enabled = 0
let g:go_fmt_command = 'goimports'
let g:go_fmt_fail_silently = 1
'''
