[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
let g:NERDTreeMinimalUI = 1
nnoremap <Leader>f :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'majutsushi/tagbar'
on_i = 1
hook_add = '''
let g:tagbar_autofocus = 1
nnoremap <Leader>x :TagbarToggle<CR>
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_add = '''
set completeopt+=noselect
let g:deoplete#enable_at_startup = 1
inoremap <expr><tab> pumvisible() ? "<C-n>" : "<TAB>"
inoremap <expr><s-tab> pumvisible() ? "<C-p>" : "<TAB>"
'''

[[plugins]]
repo = 'zchee/deoplete-go'
on_i = 1
on_ft = 'go'
build = 'make'
hook_add = '''
let g:deoplete#sources#go#gocode_binary = $GOPATH . '/bin/gocode'
let g:deoplete#sources#go#sort_class = ['package', 'func', 'type', 'var', 'const']
'''

[[plugins]]
repo = 'neomake/neomake'
hook_add = '''
autocmd! BufWritePost * Neomake
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'vim-jp/cpp-vim'
on_ft = 'cpp'

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'

[[plugins]]
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown', 'mkd', 'md']

[[plugins]]
repo = 'chriskempson/vim-tomorrow-theme'
hook_add = '''
autocmd! VimEnter * nested colorscheme Tomorrow-Night-Blue
'''

